### ISSUE TITLE
There is a bug in line number 7

### ISSUE THREAD

**Issue by Mujtaba503** [Mujtaba503/MDevops#1]
Hi Team,
There is a bug in line number 7, please get it correct.
![Devops1](https://user-images.githubusercontent.com/80738291/111260218-72fdcb00-8646-11eb-88f9-e38d588db192.png)

**Comment by bipeensinha** [comment]
I am working oin it and will upodaye

**Comment by sachin-goled** [comment]
I am working on it.

**Comment by Mujtaba503** [comment]
Thank you guys, keep me posted.

**Comment by bipeensinha** [comment]
yahoo i fix this 
![a](https://user-images.githubusercontent.com/49720823/111260324-9c1e5b80-8646-11eb-9427-7867d3aec305.png)

**Comment by Mujtaba503** [comment]
Thank you very much.
